/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { Transaction } from './models/transaction';
export type { TransactionDto } from './models/transaction-dto';
