/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Transaction {
  category?: string;
  dateCreate?: string;
  dateTransaction?: string;
  dateUpdate?: string;
  description?: string;
  id?: number;
  status?: string;
  type?: boolean;
  value?: number;
}
